import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< Updated upstream
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
  const isActive = (path) => pathname.startsWith(path);

  return (
    <>
      {/* HEADER */}
      <header className="fixed top-0 left-0 right-0 z-50 h-10 pt-2 bg-slate-800 font-bold text-slate-100 mb-0 shadow-xl">
        <div className = "flex flex-row gap-2 justify-evenly">
          <p className = "companyName" >American Backflow & Plumbing Services, Inc.</p> 
          <OnlineChecker />
        </div>
      </header>

      {/* MAIN */}
      <main className="flex-1 mt-10 mb-10 overflow-y-auto bg-gray-50 p-0">
        {children}
      </main>

      {/* FOOTER */}
      {session && (
        <footer className="fixed bottom-0 left-0 right-0 z-50 bg-slate-100 border-t border-gray-200 flex justify-around items-center h-16 shadow-md">
          <button
            onClick={handleDispatch}
            className={`flex flex-col items-center justify-center px-4 py-1 rounded-md transition ${
              isActive('/dispatch')
                ? 'bg-blue-100 text-blue-700'
                : 'text-gray-700 hover:text-blue-600 hover:bg-gray-100'
            }`}
          >
            <Home className="w-5 h-5 mb-0.5" />
            <span className="text-xs font-medium">Dispatch</span>
          </button>

          <button
            onClick={handleMore}
            className={`flex flex-col items-center justify-center px-4 py-1 rounded-md transition ${
              isActive('/more')
                ? 'bg-blue-100 text-blue-700'
                : 'text-gray-700 hover:text-blue-600 hover:bg-gray-100'
            }`}
          >
            <Layers className="w-5 h-5 mb-0.5" />
            <span className="text-xs font-medium">More</span>
          </button>

          <button
            onClick={handleLogout}
            className="flex flex-col items-center justify-center px-4 py-1 rounded-md text-gray-700 hover:text-red-600 hover:bg-gray-100 transition"
          >
            <LogOut className="w-5 h-5 mb-0.5" />
            <span className="text-xs font-medium">Logout</span>
          </button>
        </footer>
      )}
    </>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/esh7blp.css" />
        <link rel="stylesheet" href="https://use.typekit.net/bgo3voa.css" />
      </head>
      <body className="flex flex-col min-h-screen bg-white text-gray-800 overflow-hidden">
        <SessionProvider>
          <LayoutContent>{children}</LayoutContent>
        </SessionProvider>
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
